### ISSUE TITLE
Add jobs for https://www.railroad19.com/

### ISSUE THREAD

**Issue by marklocklear** [marklocklear/remote_gig#14]
https://www.railroad19.com/

**Comment by marklocklear** [comment]
Done!

**Comment by marklocklear** [comment]
Need to add description and tags also

**Comment by MCHadley** [comment]
I added a line for the description, it'll grab it when I run it in sandbox but not in get_jobs. Any ideas?

**Comment by marklocklear** [comment]
@MCHadley what is your question? Right now the description field for RR19 jobs is being populated with the line/URL rather than an actual description of the job. The job description is what allows the tags to be populated. Let me know if that helps, or if you need more info. Are you the coders league slack team? If not let me know and I can send you an invite and we can collaborate sycronously there.

**Comment by marklocklear** [comment]
https://github.com/marklocklear/remote_gig/commit/58de16819d9989bf4bc401c44f008a07eee95377
