### ISSUE TITLE
Add "email me this job" link

### ISSUE THREAD

**Issue by marklocklear** [marklocklear/remote_gig#30]
Add a share link so user can enter an email and email the job (title and url) to themselves or someone else.

**Comment by notingGone** [comment]
What is the user story? Will this be a modal?

**Comment by marklocklear** [comment]
@notingGone actually this is done. Notice I added the "..." to each job, share via twitter and FB links do not work. I added a new issue here https://github.com/marklocklear/remote_gig/issues/62
