### ISSUE TITLE
Add API to https://github.com/public-apis

### ISSUE THREAD

**Issue by marklocklear** [marklocklear/remote_gig#53]
Submit a pull request to https://github.com/public-apis to add https://remotegig.io/jobs.json to the jobs section here: https://github.com/public-apis/public-apis#jobs

**Comment by notingGone** [comment]
Does the remotegig.io API support CORS?

**Comment by marklocklear** [comment]
Yes! (I think) 🙂

**Comment by notingGone** [comment]
[Pull request submitted](https://github.com/public-apis/public-apis/pull/1131)

**Comment by marklocklear** [comment]
@notingGone thanks!
